### ISSUE TITLE
Adjust image used for "Developed-Open" tile 

### ISSUE THREAD

**Issue by dboyer** [WikiWatershed/mmw-micro#20]
Learning accessibility experts indicated that the image used for the "Developed-open" tile is not easily visible at all levels and doesn’t seem to match the pattern used to show that land cover type on the left side of the screen.

Perhaps select a new image or zoom into existing texture.

![Screen Shot 2020-05-28 at 1 46 19 PM](https://user-images.githubusercontent.com/516764/83175274-a4260280-a0e9-11ea-9292-a1fe85f98b96.png)

**Comment by dboyer** [comment]
@designmatty Could use a design consult on this.

**Comment by rajadain** [comment]
Commenting to get email notifications on activity.

**Comment by designmatty** [comment]
I created two new patterns for Developed-Open which I feel more closely relates to the description of NLCD Class 21:

**Option 1**
![Developed-open-thumb-v1](https://user-images.githubusercontent.com/1928955/87560777-d2f03c00-c689-11ea-90d1-295310f71167.png)
![Developed-open-v1](https://user-images.githubusercontent.com/1928955/87560781-d2f03c00-c689-11ea-91bd-6d288700a298.png)

**Option 2**
![Developed-open-thumb-v2](https://user-images.githubusercontent.com/1928955/87560779-d2f03c00-c689-11ea-8065-8e31577bdce1.png)
![Developed-open-v2](https://user-images.githubusercontent.com/1928955/87560784-d388d280-c689-11ea-8c00-619de31a4d8a.png)

**Comment by rajadain** [comment]
Haha I like Option 2 a lot.

**Comment by SRGDamia1** [comment]
I also like option 2.  Apart from being prettier, the playing field is probably more accurate for developed open.

Could you add a small building and/or a small paved parking area?

The NLCD classification for developed open can include up to 20% impervious surface.  That's a fair amount "open" land that's really paved.  Both the SLAMM model and the TR-55 model curve numbers use 20% impervious in the runoff calculation.  It's based on data from the development of the SLAMM model showing that most parks/cemeteries/playing fields/etc have approximately that amount of impervious coverage.

**Comment by designmatty** [comment]
Thanks @SRGDamia1 for the suggestion. I added a paved area to the image for better accuracy.

![Developed-open-v3](https://user-images.githubusercontent.com/1928955/88576742-e00b1480-d013-11ea-898c-c11fc577dc68.png)
