### ISSUE TITLE
Shortening screen does not shorten background image and arrows

### ISSUE THREAD

**Issue by dboyer** [WikiWatershed/mmw-micro#22]
![Screen Shot 2020-05-28 at 1 53 07 PM](https://user-images.githubusercontent.com/516764/83175891-a6d52780-a0ea-11ea-9647-bd6de849baeb.png)

**Comment by dboyer** [comment]
@designmatty Will need some design time here.

**Comment by rajadain** [comment]
Commenting to get email notifications on activity.

**Comment by rajadain** [comment]
Fixed in #27
