### ISSUE TITLE
Replace Google Analytics tag

### ISSUE THREAD

**Issue by HeatherBrooks** [WikiWatershed/mmw-micro#32]
The Google Analytics UA tag on the runoff simulation stopped collecting data in mid-October. It needs to be replaced with the attached GA4 gtag.js. (Similar to Model My Watershed #[3581](https://github.com/WikiWatershed/model-my-watershed/issues/3581).) Thank you!
[runoff-simulation-ga4-tag.txt](https://github.com/WikiWatershed/mmw-micro/files/13244100/runoff-simulation-ga4-tag.txt)

**Comment by rajadain** [comment]
Updated on production now: https://runoff.modelmywatershed.org/
