### ISSUE TITLE
Update static model output with latest TR-55 results

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/mmw-micro#8]
When https://github.com/WikiWatershed/model-my-watershed/issues/1923 is complete, update and release the micro site with new values generated from the latest TR-55 version.

**Comment by rajadain** [comment]
Use this script to generate the new CSV [tr55/makeMiniAppTable.py](https://github.com/WikiWatershed/tr-55/blob/develop/tr55/makeMiniAppTable.py)
